# Generated by Django 5.1.2 on 2024-10-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('persons', models.CharField(blank=True, max_length=255)),
                ('follow_up', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('dates', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(max_length=255)),
            ],
        ),
    ]
